/* data.js — base de codes multi-jeux GTA. Consommé par game.html (?g=<id>). */
window.GAMES = {

  sanandreas: {
    title:"San Andreas", short:"GTA SA", accent:"#86C34A", accentDim:"#5c8a32",
    eyebrow:"GTA: San Andreas · État de San Andreas · 2004",
    h1:'Triches<span class="l2">San Andreas</span>',
    lede:"CJ de retour à Los Santos. Codes clavier PC et combos manette. Appuie pour copier.",
    warn:"Activer un code peut bloquer certains succès et empêcher le 100%. Certains codes ne se désactivent pas — sauvegarde avant.",
    platforms:[
      {id:"pc",   label:"PC (clavier)", icon:"⌨", type:"word"},
      {id:"ps2",  label:"PlayStation",  icon:"▲", type:"ps"},
      {id:"xbox", label:"Xbox",         icon:"✛", type:"xbox"}
    ],
    howto:{
      pc:"<b>PC :</b> tape le code en toutes lettres pendant le jeu (pas de menu à ouvrir). Un message confirme.",
      ps2:"<b>PlayStation :</b> entre la combinaison manette directement en jeu (PS2/PS3/PS4).",
      xbox:"<b>Xbox :</b> entre la combinaison manette en jeu (Xbox/360/One)."
    },
    cats:[
      {id:"combat",label:"Survie & combat"},
      {id:"player",label:"Joueur"},
      {id:"veh",   label:"Véhicules"},
      {id:"world", label:"Monde & météo"},
      {id:"fun",   label:"Chaos & fun"}
    ],
    cheats: [
{"name":"Santé, armure et 250 000 $","cat":"combat","pc":"HESOYAM","ps2":"R1, R2, L1, X, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RB, RT, LB, A, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Santé infinie (invincibilité partielle)","cat":"combat","pc":"BAGUVIX","ps2":null,"xbox":null},
{"name":"Munitions infinies","cat":"combat","pc":"WANRLTW","ps2":null,"xbox":null},
{"name":"Armes niveau 1 (pack de base)","cat":"combat","pc":"LXGIWYL","ps2":"R1, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RB, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Armes niveau 2 (pack pro)","cat":"combat","pc":"KJKSZPJ","ps2":"R1, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Gauche","xbox":"RB, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Gauche"},
{"name":"Armes niveau 3 (pack explosifs)","cat":"combat","pc":"UZUMYMW","ps2":"R1, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Bas","xbox":"RB, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Bas"},
{"name":"Mode tueur (deux flingues, tirs illimités)","cat":"combat","pc":"NCSGDAG","ps2":null,"xbox":null},
{"name":"Jamais recherché par la police","cat":"combat","pc":"AEZAKMI","ps2":null,"xbox":null},
{"name":"Baisser le niveau de recherche","cat":"combat","pc":"ASNAEB","ps2":"R1, R1, Rond, R2, Haut, Bas, Haut, Bas, Haut, Bas","xbox":"RB, RB, B, RT, Haut, Bas, Haut, Bas, Haut, Bas"},
{"name":"Augmenter le niveau de recherche (+2 étoiles)","cat":"combat","pc":"OSRBLHH","ps2":"R1, R1, Rond, R2, Gauche, Droite, Gauche, Droite, Gauche, Droite","xbox":"RB, RB, B, RT, Gauche, Droite, Gauche, Droite, Gauche, Droite"},
{"name":"Six étoiles de recherche","cat":"combat","pc":"LJSPQK","ps2":"Rond, Droite, Rond, Droite, Gauche, Carré, X, Bas","xbox":"B, Droite, B, Droite, Gauche, X, A, Bas"},
{"name":"Tank Rhino","cat":"veh","pc":"AIWPRTON","ps2":"Rond, Rond, L1, Rond, Rond, Rond, L1, L2, R1, Triangle, Rond, Triangle","xbox":"B, B, LB, B, B, B, LB, LT, RB, Y, B, Y"},
{"name":"Bloodring Banger (voiture de course)","cat":"veh","pc":"CQZIJMB","ps2":"Bas, R1, Rond, L2, L2, X, R1, L1, Gauche, Gauche","xbox":"Bas, RB, B, LT, LT, A, RB, LB, Gauche, Gauche"},
{"name":"Rancher (4x4)","cat":"veh","pc":"JQNTDMH","ps2":"Haut, Droite, Droite, L1, Droite, Haut, Carré, L2","xbox":"Haut, Droite, Droite, LB, Droite, Haut, X, LT"},
{"name":"Hotring Racer 1","cat":"veh","pc":"PDNEJOH","ps2":"R1, Rond, R2, Droite, L1, L2, X, X, Carré, R1","xbox":"RB, B, RT, Droite, LB, LT, A, A, X, RB"},
{"name":"Hotring Racer 2","cat":"veh","pc":"VPJTQWV","ps2":"R2, L1, Rond, Droite, L1, R1, Droite, Haut, Rond, R2","xbox":"RT, LB, B, Droite, LB, RB, Droite, Haut, B, RT"},
{"name":"Romero (corbillard)","cat":"veh","pc":"AQTBCODX","ps2":"Bas, R2, Bas, R1, L2, Gauche, R1, L1, Gauche, Droite","xbox":"Bas, RT, Bas, RB, LT, Gauche, RB, LB, Gauche, Droite"},
{"name":"Stretch (limousine)","cat":"veh","pc":"KRIJEBR","ps2":"R2, Haut, L2, Gauche, Gauche, R1, L1, Rond, Droite","xbox":"RT, Haut, LT, Gauche, Gauche, RB, LB, B, Droite"},
{"name":"Trashmaster (camion poubelle)","cat":"veh","pc":"UBHYZHQ","ps2":"Rond, R1, Rond, R1, Gauche, Gauche, R1, L1, Rond, Droite","xbox":"B, RB, B, RB, Gauche, Gauche, RB, LB, B, Droite"},
{"name":"Caddy (voiturette de golf)","cat":"veh","pc":"RZHSUEW","ps2":"Rond, L1, Haut, R1, L2, X, R1, L1, Rond, X","xbox":"B, LB, Haut, RB, LT, A, RB, LB, B, A"},
{"name":"Hunter (hélicoptère de combat)","cat":"veh","pc":"OHDUDE","ps2":"Rond, X, L1, Rond, Rond, L1, Rond, R1, R2, L2, L1, L1","xbox":"B, A, LB, B, B, LB, B, RB, RT, LT, LB, LB"},
{"name":"Hydra (jet de combat)","cat":"veh","pc":"JUMPJET","ps2":"Triangle, Triangle, Carré, Rond, X, L1, L1, Bas, Haut","xbox":"Y, Y, X, B, A, LB, LB, Bas, Haut"},
{"name":"Jetpack","cat":"veh","pc":"ROCKETMAN","ps2":"L1, L2, R1, R2, Haut, Bas, Gauche, Droite, L1, L2, R1, R2, Haut, Bas, Gauche, Droite","xbox":"LB, LT, RB, RT, Haut, Bas, Gauche, Droite, LB, LT, RB, RT, Haut, Bas, Gauche, Droite"},
{"name":"Vortex (aéroglisseur)","cat":"veh","pc":"KGGGDKP","ps2":"Triangle, Triangle, Carré, Rond, X, L1, L2, Bas, Bas","xbox":"Y, Y, X, B, A, LB, LT, Bas, Bas"},
{"name":"Quad","cat":"veh","pc":"AKJJYGLC","ps2":"Gauche, Gauche, Bas, Bas, Haut, Haut, Carré, Rond, Triangle, R1, R2","xbox":"Gauche, Gauche, Bas, Bas, Haut, Haut, X, B, Y, RB, RT"},
{"name":"Tanker (camion citerne)","cat":"veh","pc":"AMOMHRER","ps2":"R1, Haut, Gauche, Droite, R2, Haut, Droite, Carré, Droite, L2, L1, L1","xbox":"RB, Haut, Gauche, Droite, RT, Haut, Droite, X, Droite, LT, LB, LB"},
{"name":"Dozer (bulldozer)","cat":"veh","pc":"EEGCYXT","ps2":"R2, L1, L1, Droite, Droite, Haut, Haut, X, L1, Gauche","xbox":"RT, LB, LB, Droite, Droite, Haut, Haut, A, LB, Gauche"},
{"name":"Stunt Plane (avion de voltige)","cat":"veh","pc":"URKQSRK","ps2":"Rond, Haut, L1, L2, Bas, R1, L1, L1, Gauche, Gauche, X, Triangle","xbox":"B, Haut, LB, LT, Bas, RB, LB, LB, Gauche, Gauche, A, Y"},
{"name":"Monster (monster truck)","cat":"veh","pc":"AGBDLCID","ps2":"Droite, Haut, R1, R1, R1, Bas, Triangle, Triangle, X, Rond, L1, L1","xbox":"Droite, Haut, RB, RB, RB, Bas, Y, Y, A, B, LB, LB"},
{"name":"Temps ensoleillé","cat":"world","pc":"MGHXYR","ps2":"R2, X, L1, L1, L2, L2, L2, Triangle","xbox":"RT, A, LB, LB, LT, LT, LT, Y"},
{"name":"Temps très ensoleillé","cat":"world","pc":"ICIKPYH","ps2":"R2, X, L1, L1, L2, L2, L2, Bas","xbox":"RT, A, LB, LB, LT, LT, LT, Bas"},
{"name":"Temps couvert (nuageux)","cat":"world","pc":"ALNSFMZO","ps2":"R2, X, L1, L1, L2, L2, L2, Carré","xbox":"RT, A, LB, LB, LT, LT, LT, X"},
{"name":"Temps brumeux","cat":"world","pc":"CFVFGMJ","ps2":"R2, X, L1, L1, L2, L2, L2, X","xbox":"RT, A, LB, LB, LT, LT, LT, A"},
{"name":"Tempête de sable","cat":"world","pc":"CWJXUOC","ps2":"Haut, Bas, L1, L1, L2, L2, L1, L2, R1, R2","xbox":"Haut, Bas, LB, LB, LT, LT, LB, LT, RB, RT"},
{"name":"Temps orageux","cat":"world","pc":"AUIFRVQS","ps2":"R2, X, L1, L1, L2, L2, L2, Rond","xbox":"RT, A, LB, LB, LT, LT, LT, B"},
{"name":"Toujours minuit","cat":"world","pc":"XJVSNAJ","ps2":"Carré, L1, R1, Droite, X, Haut, L1, Gauche, Gauche","xbox":"X, LB, RB, Droite, A, Haut, LB, Gauche, Gauche"},
{"name":"Ciel orange (21h00)","cat":"world","pc":"OFVIAC","ps2":"Gauche, Gauche, L2, R1, Droite, Carré, Carré, L1, L2, X","xbox":"Gauche, Gauche, LT, RB, Droite, X, X, LB, LT, A"},
{"name":"Super saut","cat":"player","pc":"LFGMHAL","ps2":"Haut, Haut, Triangle, Triangle, Haut, Haut, Gauche, Droite, Carré, R2, R2","xbox":"Haut, Haut, Y, Y, Haut, Haut, Gauche, Droite, X, RT, RT"},
{"name":"Super coup de poing","cat":"player","pc":"IAVENJQ","ps2":"Haut, Gauche, X, Triangle, R1, Rond, Rond, Rond, L2","xbox":"Haut, Gauche, A, Y, RB, B, B, B, LT"},
{"name":"Oxygène infini (respiration sous l'eau)","cat":"player","pc":"CVWKXAM","ps2":"Bas, Gauche, L1, Bas, Bas, R2, Bas, L2, Bas","xbox":"Bas, Gauche, LB, Bas, Bas, RT, Bas, LT, Bas"},
{"name":"Muscle maximum","cat":"player","pc":"JYSDSOD","ps2":"Triangle, Haut, Haut, Gauche, Droite, Carré, Rond, Gauche","xbox":"Y, Haut, Haut, Gauche, Droite, X, B, Gauche"},
{"name":"Gras maximum","cat":"player","pc":"BTCDBCB","ps2":"Triangle, Haut, Haut, Gauche, Droite, Carré, Rond, Bas","xbox":"Y, Haut, Haut, Gauche, Droite, X, B, Bas"},
{"name":"Respect maximum","cat":"player","pc":"OGXSDAG","ps2":"L1, R1, Triangle, Bas, R2, X, L1, Haut, L2, L2, L1, L1","xbox":"LB, RB, Y, Bas, RT, A, LB, Haut, LT, LT, LB, LB"},
{"name":"Sex-appeal maximum","cat":"player","pc":"EHIBXQS","ps2":"Rond, Triangle, Triangle, Haut, Rond, R1, L2, Haut, Triangle, L1, L1, L1","xbox":"B, Y, Y, Haut, B, RB, LT, Haut, Y, LB, LB, LB"},
{"name":"Jamais affamé","cat":"player","pc":"AEDUWNV","ps2":null,"xbox":null},
{"name":"Jeu plus rapide","cat":"world","pc":"PPGWJHT","ps2":"Triangle, Haut, Droite, Bas, L2, L1, Carré","xbox":"Y, Haut, Droite, Bas, LT, LB, X"},
{"name":"Jeu plus lent","cat":"world","pc":"LIYOAAY","ps2":"Triangle, Haut, Droite, Bas, Carré, R2, R1","xbox":"Y, Haut, Droite, Bas, X, RT, RB"},
{"name":"Mode adrénaline (temps ralenti au combat)","cat":"fun","pc":"MUNASEF","ps2":"Haut, Haut, Bas, Bas, Gauche, Droite, Gauche, Droite, Rond, X","xbox":"Haut, Haut, Bas, Bas, Gauche, Droite, Gauche, Droite, B, A"},
{"name":"Conducteurs agressifs","cat":"world","pc":"YLTEICZ","ps2":"R2, Rond, R1, L2, Gauche, R1, L1, R2, L2","xbox":"RT, B, RB, LT, Gauche, RB, LB, RT, LT"},
{"name":"Les piétons t'attaquent","cat":"world","pc":"BAGOWPG","ps2":"Bas, Haut, Haut, Haut, X, R2, R1, L2, L2","xbox":"Bas, Haut, Haut, Haut, A, RT, RB, LT, LT"},
{"name":"Émeute des piétons (chaos)","cat":"fun","pc":"IOJUFZN","ps2":"Bas, Gauche, Haut, Gauche, X, R2, R1, L2, L1","xbox":"Bas, Gauche, Haut, Gauche, A, RT, RB, LT, LB"},
{"name":"Les piétons sont armés","cat":"fun","pc":"FOOOXFT","ps2":"R2, R1, X, Triangle, X, Triangle, Haut, Bas","xbox":"RT, RB, A, Y, A, Y, Haut, Bas"},
{"name":"Circulation rose","cat":"fun","pc":"LLQPFBN","ps2":"Rond, L1, Bas, L2, Gauche, X, R1, L1, Droite, Rond","xbox":"B, LB, Bas, LT, Gauche, A, RB, LB, Droite, B"},
{"name":"Circulation noire","cat":"fun","pc":"IOWDLAC","ps2":"Rond, L2, Haut, R1, Gauche, X, R1, L1, Gauche, Rond","xbox":"B, LT, Haut, RB, Gauche, A, RB, LB, Gauche, B"},
{"name":"Voitures volantes","cat":"fun","pc":"RIPAZHA","ps2":"Haut, Bas, L1, R1, L1, Droite, Gauche, L1, Gauche","xbox":"Haut, Bas, LB, RB, LB, Droite, Gauche, LB, Gauche"},
{"name":"Voitures roulant sur l'eau","cat":"fun","pc":"GKPNMQ","ps2":"Droite, R2, Rond, R1, L2, Carré, R1, R2","xbox":"Droite, RT, B, RB, LT, X, RB, RT"},
{"name":"Tous les feux au vert","cat":"world","pc":"ZEIIVG","ps2":null,"xbox":null}
    ]
  },

  vicecity: {
    title:"Vice City", short:"GTA VC", accent:"#FF5FA2", accentDim:"#b83b73",
    eyebrow:"GTA: Vice City · Vice City · 2002",
    h1:'Triches<span class="l2">Vice City</span>',
    lede:"Miami années 80, néons et pastel. Codes clavier PC et combos manette.",
    warn:"Activer un code peut bloquer des succès et la progression. Certains ne se désactivent pas — sauvegarde avant.",
    platforms:[
      {id:"pc",   label:"PC (clavier)", icon:"⌨", type:"word"},
      {id:"ps2",  label:"PlayStation",  icon:"▲", type:"ps"},
      {id:"xbox", label:"Xbox",         icon:"✛", type:"xbox"}
    ],
    howto:{
      pc:"<b>PC :</b> tape le code en toutes lettres pendant le jeu. Un message confirme.",
      ps2:"<b>PlayStation :</b> entre la combinaison manette en jeu (PS2/PS3/PS4).",
      xbox:"<b>Xbox :</b> entre la combinaison manette en jeu."
    },
    cats:[
      {id:"combat",label:"Survie & combat"},
      {id:"player",label:"Joueur"},
      {id:"veh",   label:"Véhicules"},
      {id:"world", label:"Monde & météo"},
      {id:"fun",   label:"Chaos & fun"}
    ],
    cheats: [
{"name":"Santé pleine","cat":"combat","pc":"ASPIRINE","ps2":"R1, R2, L1, Rond, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RB, RT, LB, B, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Armure pleine","cat":"combat","pc":"PRECIOUSPROTECTION","ps2":"R1, R2, L1, X, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RB, RT, LB, A, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Jeu d'armes 1 (léger)","cat":"combat","pc":"THUGSTOOLS","ps2":"R1, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RB, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Jeu d'armes 2 (pro)","cat":"combat","pc":"PROFESSIONALTOOLS","ps2":"R1, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Gauche","xbox":"RB, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Gauche"},
{"name":"Jeu d'armes 3 (lourd)","cat":"combat","pc":"NUTTERTOOLS","ps2":"R1, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Bas","xbox":"RB, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Bas, Bas"},
{"name":"Augmenter recherche","cat":"combat","pc":"YOUWONTTAKEMEALIVE","ps2":"R1, R1, Rond, R2, Gauche, Droite, Gauche, Droite, Gauche, Droite","xbox":"RB, RB, B, RT, Gauche, Droite, Gauche, Droite, Gauche, Droite"},
{"name":"Effacer recherche","cat":"combat","pc":"LEAVEMEALONE","ps2":"R1, R1, Rond, R2, Haut, Bas, Haut, Bas, Haut, Bas","xbox":"RB, RB, B, RT, Haut, Bas, Haut, Bas, Haut, Bas"},
{"name":"Se suicider","cat":"combat","pc":"ICANTTAKEITANYMORE","ps2":"Droite, L2, Bas, R1, Gauche, Gauche, R1, L1, L2, L1","xbox":"Droite, LT, Bas, RB, Gauche, Gauche, RB, LB, LT, LB"},
{"name":"Faire exploser les voitures","cat":"combat","pc":"BIGBANG","ps2":"R2, L2, R1, L1, L2, R2, Carré, Triangle, Rond, Triangle, L2, L1","xbox":"RT, LT, RB, LB, LT, RT, X, Y, B, Y, LT, LB"},
{"name":"Spawn Tank (Rhino)","cat":"veh","pc":"PANZER","ps2":"Rond, Rond, L1, Rond, Rond, Rond, L1, L2, R1, Triangle, Rond, Triangle","xbox":"B, B, LB, B, B, B, LB, LT, RB, Y, B, Y"},
{"name":"Spawn Bloodring Banger 1","cat":"veh","pc":"TRAVELINSTYLE","ps2":"Bas, R1, Rond, L2, L2, X, R1, L1, Gauche, Gauche","xbox":"Bas, RB, B, LT, LT, A, RB, LB, Gauche, Gauche"},
{"name":"Spawn Bloodring Banger 2","cat":"veh","pc":"GETTHEREQUICKLY","ps2":"Haut, Droite, Droite, L1, Droite, Haut, Carré, L2","xbox":"Haut, Droite, Droite, LB, Droite, Haut, X, LT"},
{"name":"Spawn Hotring Racer 1","cat":"veh","pc":"GETTHEREFAST","ps2":"R1, Rond, R2, Droite, L1, L2, X, X, Carré, R1","xbox":"RB, B, RT, Droite, LB, LT, A, A, X, RB"},
{"name":"Spawn Hotring Racer 2","cat":"veh","pc":"GETTHEREVERYFASTINDEED","ps2":"R2, L1, Rond, Droite, L1, R1, Droite, Haut, Rond, R2","xbox":"RT, LB, B, Droite, LB, RB, Droite, Haut, B, RT"},
{"name":"Spawn Corbillard (Romero)","cat":"veh","pc":"THELASTRIDE","ps2":"Bas, R2, Bas, R1, L2, Gauche, R1, L1, Gauche, Droite","xbox":"Bas, RT, Bas, RB, LT, Gauche, RB, LB, Gauche, Droite"},
{"name":"Spawn Love Fist (limousine)","cat":"veh","pc":"ROCKANDROLLCAR","ps2":"R2, Haut, L2, Gauche, Gauche, R1, L1, Rond, Droite","xbox":"RT, Haut, LT, Gauche, Gauche, RB, LB, B, Droite"},
{"name":"Spawn Trashmaster (benne)","cat":"veh","pc":"RUBBISHCAR","ps2":"Rond, R1, Rond, R1, Gauche, Gauche, R1, L1, Rond, Droite","xbox":"B, RB, B, RB, Gauche, Gauche, RB, LB, B, Droite"},
{"name":"Spawn Sabre Turbo","cat":"veh","pc":"GETTHEREAMAZINGLYFAST","ps2":"Droite, L2, Bas, L2, L2, X, R1, L1, Rond, Gauche","xbox":"Droite, LT, Bas, LT, LT, A, RB, LB, B, Gauche"},
{"name":"Spawn Caddy (voiturette golf)","cat":"veh","pc":"BETTERTHANWALKING","ps2":"Rond, L1, Haut, R1, L2, X, R1, L1, Rond, X","xbox":"B, LB, Haut, RB, LT, A, RB, LB, B, A"},
{"name":"Voitures roses","cat":"veh","pc":"AHAIRDRESSERSCAR","ps2":"Rond, L1, Bas, L2, Gauche, X, R1, L1, Droite, X","xbox":"B, LB, Bas, LT, Gauche, A, RB, LB, Droite, A"},
{"name":"Voitures noires","cat":"veh","pc":"IWANTITPAINTEDBLACK","ps2":"Rond, L2, Haut, R1, Gauche, X, R1, L1, Gauche, Rond","xbox":"B, LT, Haut, RB, Gauche, A, RB, LB, Gauche, B"},
{"name":"Voitures invisibles","cat":"veh","pc":"WHEELSAREALLINEED","ps2":"Triangle, L1, Triangle, R2, Carré, L1, L1","xbox":"Y, LB, Y, RT, X, LB, LB"},
{"name":"Ailes sur l'avion Dodo","cat":"veh","pc":"COMEFLYWITHME","ps2":"Droite, R2, Rond, R1, L2, Bas, L1, R1","xbox":"Droite, RT, B, RB, LT, Bas, LB, RB"},
{"name":"Meilleure tenue de route","cat":"veh","pc":"GRIPISEVERYTHING","ps2":"Triangle, R1, R1, Gauche, R1, L1, R2, L1","xbox":"Y, RB, RB, Gauche, RB, LB, RT, LB"},
{"name":"Vitesse de pointe accrue","cat":"veh","pc":"GREENLIGHT","ps2":"Droite, R1, Haut, L2, L2, Gauche, R1, L1, R1, R1","xbox":"Droite, RB, Haut, LT, LT, Gauche, RB, LB, RB, RB"},
{"name":"Voitures flottent sur l'eau","cat":"veh","pc":"SEAWAYS","ps2":"Droite, R2, Rond, R1, L2, Carré, R1, R2","xbox":"Droite, RT, B, RB, LT, X, RB, RT"},
{"name":"Grosses roues","cat":"veh","pc":"LOADSOFLITTLETHINGS","ps2":"R1, X, Triangle, Droite, R2, Carré, Haut, Bas, Carré","xbox":"RB, A, Y, Droite, RT, X, Haut, Bas, X"},
{"name":"Temps ensoleillé","cat":"world","pc":"ALOVELYDAY","ps2":"R2, X, L1, L1, L2, L2, L2, Bas","xbox":"RT, A, LB, LB, LT, LT, LT, Bas"},
{"name":"Temps nuageux","cat":"world","pc":"APLEASANTDAY","ps2":"R2, X, L1, L1, L2, L2, L2, Triangle","xbox":"RT, A, LB, LB, LT, LT, LT, Y"},
{"name":"Temps très nuageux","cat":"world","pc":"ABITDRIEG","ps2":"R2, X, L1, L1, L2, L2, L2, Carré","xbox":"RT, A, LB, LB, LT, LT, LT, X"},
{"name":"Temps orageux","cat":"world","pc":"CATSANDDOGS","ps2":"R2, X, L1, L1, L2, L2, L2, Rond","xbox":"RT, A, LB, LB, LT, LT, LT, B"},
{"name":"Temps brumeux (brouillard)","cat":"world","pc":"CANTSEEATHING","ps2":"R2, X, L1, L1, L2, L2, L2, X","xbox":"RT, A, LB, LB, LT, LT, LT, A"},
{"name":"Accélérer le temps","cat":"world","pc":"LIFEISPASSINGMEBY","ps2":"Rond, Rond, L1, Carré, L1, Carré, Carré, Carré, L1, Triangle, Rond, Triangle","xbox":"B, B, LB, X, LB, X, X, X, LB, Y, B, Y"},
{"name":"Jeu plus rapide","cat":"world","pc":"ONSPEED","ps2":null,"xbox":null},
{"name":"Jeu plus lent","cat":"world","pc":"BOOOOORING","ps2":"Triangle, Haut, Droite, Bas, Carré, R2, R1","xbox":"Y, Haut, Droite, Bas, X, RT, RB"},
{"name":"Émeute (piétons se battent)","cat":"fun","pc":"FIGHTFIGHTFIGHT","ps2":"Bas, Gauche, Haut, Gauche, X, R2, R1, L2, L1","xbox":"Bas, Gauche, Haut, Gauche, A, RT, RB, LT, LB"},
{"name":"Les piétons t'attaquent","cat":"fun","pc":"NOBODYLIKESME","ps2":"Bas, Haut, Haut, Haut, X, R2, R1, L2, L2","xbox":"Bas, Haut, Haut, Haut, A, RT, RB, LT, LT"},
{"name":"Piétons armés","cat":"fun","pc":"OURGODGIVENRIGHTTOBEARARMS","ps2":"R2, R1, X, Triangle, X, Triangle, Haut, Bas","xbox":"RT, RB, A, Y, A, Y, Haut, Bas"},
{"name":"Conducteurs agressifs","cat":"world","pc":"MIAMITRAFFIC","ps2":"R2, Rond, R1, L2, Gauche, R1, L1, R2, L2","xbox":"RT, B, RB, LT, Gauche, RB, LB, RT, LT"},
{"name":"Tous les feux au vert","cat":"world","pc":"GREENLIGHT","ps2":"Droite, R1, Haut, L2, L2, Gauche, R1, L1, R1, R1","xbox":"Droite, RB, Haut, LT, LT, Gauche, RB, LB, RB, RB"},
{"name":"Les filles te suivent (aimant)","cat":"player","pc":"FANNYMAGNET","ps2":"Rond, X, L1, L1, R2, X, X, Rond, Triangle","xbox":"B, A, LB, LB, RT, A, A, B, Y"},
{"name":"Filles en bikini avec armes","cat":"fun","pc":"CHICKSWITHGUNS","ps2":"Droite, L1, Rond, L2, Gauche, X, R1, L1, L1, X","xbox":"Droite, LB, B, LT, Gauche, A, RB, LB, LB, A"},
{"name":"Changer de tenue","cat":"player","pc":"DEEPFRIEDMARSBARS","ps2":"Droite, Droite, Gauche, Haut, L1, L2, Gauche, Haut, Bas, Droite","xbox":"Droite, Droite, Gauche, Haut, LB, LT, Gauche, Haut, Bas, Droite"}
    ]
  },

  gta3: {
    title:"GTA III", short:"GTA III", accent:"#8AA6BA", accentDim:"#5f7482",
    eyebrow:"Grand Theft Auto III · Liberty City · 2001",
    h1:'Triches<span class="l2">GTA III</span>',
    lede:"Le premier GTA en 3D. Codes clavier PC et combos manette.",
    warn:"Activer un code peut bloquer des succès et corrompre certaines missions. Sauvegarde avant d'essayer.",
    platforms:[
      {id:"pc",   label:"PC (clavier)", icon:"⌨", type:"word"},
      {id:"ps2",  label:"PlayStation",  icon:"▲", type:"ps"},
      {id:"xbox", label:"Xbox",         icon:"✛", type:"xbox"}
    ],
    howto:{
      pc:"<b>PC :</b> tape le code en toutes lettres pendant le jeu. Un message confirme.",
      ps2:"<b>PlayStation :</b> entre la combinaison manette en jeu (PS2/PS3).",
      xbox:"<b>Xbox :</b> entre la combinaison manette en jeu."
    },
    cats:[
      {id:"combat",label:"Survie & combat"},
      {id:"player",label:"Joueur"},
      {id:"veh",   label:"Véhicules"},
      {id:"world", label:"Monde & météo"},
      {id:"fun",   label:"Chaos & fun"}
    ],
    cheats: [
{"name":"Vie complète","cat":"player","pc":"GESUNDHEIT","ps2":"R2, R2, L1, R1, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RT, RT, LB, RB, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Armure complète","cat":"player","pc":"TORTOISE","ps2":"R2, R2, L1, L2, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RT, RT, LB, LT, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Toutes les armes","cat":"combat","pc":"GUNSGUNSGUNS","ps2":"R2, R2, L1, R2, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RT, RT, LB, RT, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"250 000 $","cat":"player","pc":"IFIWEREARICHMAN","ps2":"R2, R2, L1, L1, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut","xbox":"RT, RT, LB, LB, Gauche, Bas, Droite, Haut, Gauche, Bas, Droite, Haut"},
{"name":"Baisser le niveau de recherche","cat":"world","pc":"NOPOLICEPLEASE","ps2":"R2, R2, L1, R2, Haut, Bas, Haut, Bas, Haut, Bas","xbox":"RT, RT, LB, RT, Haut, Bas, Haut, Bas, Haut, Bas"},
{"name":"Monter le niveau de recherche","cat":"world","pc":"MOREPOLICEPLEASE","ps2":"R2, R2, L1, R2, Gauche, Droite, Gauche, Droite, Gauche, Droite","xbox":"RT, RT, LB, RT, Gauche, Droite, Gauche, Droite, Gauche, Droite"},
{"name":"Char d'assaut (tank)","cat":"veh","pc":"GIVEUSATANK","ps2":"Rond, Rond, Rond, Rond, Rond, Rond, R1, L2, L1, Triangle, Rond, Triangle","xbox":"B, B, B, B, B, B, RB, LT, LB, Y, B, Y"},
{"name":"Exploser tous les véhicules","cat":"veh","pc":"BANGBANGBANG","ps2":"L2, R2, L1, R1, L2, R2, Triangle, Carré, Rond, Triangle, L2, L1","xbox":"LT, RT, LB, RB, LT, RT, Y, X, B, Y, LT, LB"},
{"name":"Voitures volantes","cat":"veh","pc":"CHITTYCHITTYBB","ps2":"Droite, R2, Rond, R1, L2, Bas, L1, R1","xbox":"Droite, RT, B, RB, LT, Bas, LB, RB"},
{"name":"Voitures invisibles","cat":"veh","pc":"ANICESETOFWHEELS","ps2":null,"xbox":null},
{"name":"Meilleure tenue de route","cat":"veh","pc":"CORNERSLIKEMAD","ps2":null,"xbox":null},
{"name":"Piétons t'attaquent","cat":"fun","pc":"NOBODYLIKESME","ps2":"Bas, Haut, Gauche, Haut, X, R1, R2, L1, L2","xbox":"Bas, Haut, Gauche, Haut, A, RB, RT, LB, LT"},
{"name":"Piétons s'entretuent","cat":"fun","pc":"ITSALLGOINGMAAAD","ps2":"Bas, Haut, Gauche, Haut, X, R1, R2, L2, L1","xbox":"Bas, Haut, Gauche, Haut, A, RB, RT, LT, LB"},
{"name":"Piétons armés","cat":"fun","pc":"WEAPONSFORALL","ps2":"R2, R1, Triangle, X, L2, L1, Haut, Bas","xbox":"RT, RB, Y, A, LT, LB, Haut, Bas"},
{"name":"Membres arrachés (gore)","cat":"fun","pc":"NASTYLIMBSCHEAT","ps2":null,"xbox":null},
{"name":"Météo ensoleillée","cat":"world","pc":"SKINCANCERFORME","ps2":"L1, L2, R1, R2, R2, R1, L2, Triangle","xbox":"LB, LT, RB, RT, RT, RB, LT, Y"},
{"name":"Météo nuageuse","cat":"world","pc":"ILIKESCOTLAND","ps2":"L1, L2, R1, R2, R2, R1, L2, Carré","xbox":"LB, LT, RB, RT, RT, RB, LT, X"},
{"name":"Météo pluvieuse","cat":"world","pc":"ILOVESCOTLAND","ps2":"L1, L2, R1, R2, R2, R1, L2, Rond","xbox":"LB, LT, RB, RT, RT, RB, LT, B"},
{"name":"Météo brouillard","cat":"world","pc":"PEASOUP","ps2":"L1, L2, R1, R2, R2, R1, L2, X","xbox":"LB, LT, RB, RT, RT, RB, LT, A"},
{"name":"Temps plus rapide","cat":"world","pc":"MADWEATHER","ps2":"Rond, Rond, Rond, Carré, Carré, Carré, Carré, Carré, L1, Triangle, Rond, Triangle","xbox":"B, B, B, X, X, X, X, X, LB, Y, B, Y"},
{"name":"Jeu accéléré","cat":"fun","pc":"TIMEFLIESWHENYOU","ps2":null,"xbox":null},
{"name":"Ralenti (slow motion)","cat":"fun","pc":"BOOOOORING","ps2":"Triangle, Haut, Droite, Bas, Carré, R1, R2","xbox":"Y, Haut, Droite, Bas, X, RB, RT"}
    ]
  },

  gta4: {
    title:"GTA IV", short:"GTA IV", accent:"#E0894A", accentDim:"#a35f2e",
    eyebrow:"Grand Theft Auto IV · Liberty City · 2008",
    h1:'Triches<span class="l2">GTA IV</span>',
    lede:"Les codes s'activent en composant un numéro sur le téléphone de Niko. Même numéro sur PS3, Xbox 360 et PC.",
    warn:"Composer un code désactive certains succès/trophées pour la sauvegarde active (mais n'empêche pas le 100%). Le service ZiT est sans risque.",
    platforms:[
      {id:"phone", label:"Téléphone", icon:"📞", type:"phone"}
    ],
    howto:{
      phone:"<b>Téléphone :</b> sors le portable de Niko, compose le numéro puis appelle. L'effet est immédiat."
    },
    cats:[
      {id:"combat",label:"Survie & combat"},
      {id:"veh",   label:"Véhicules"},
      {id:"world", label:"Monde & météo"},
      {id:"fun",   label:"Divers"}
    ],
    cheats: [
{"name":"Soigner Niko (santé + armure)","cat":"combat","phone":"362-555-0100","note":"répare aussi le véhicule"},
{"name":"Santé + armure + armes avancées","cat":"combat","phone":"482-555-0100","note":"répare le véhicule"},
{"name":"Armes de base (pack)","cat":"combat","phone":"486-555-0150","note":"batte, pistolet, pompe, MP5, M4, sniper, RPG, grenades"},
{"name":"Armes avancées (pack complet)","cat":"combat","phone":"486-555-0100","note":null},
{"name":"Effacer le niveau de recherche","cat":"combat","phone":"267-555-0100","note":null},
{"name":"Augmenter le niveau de recherche","cat":"combat","phone":"267-555-0150","note":null},
{"name":"Changer la météo","cat":"world","phone":"468-555-0100","note":"fait défiler soleil, pluie, brouillard…"},
{"name":"Identifier la chanson (service ZiT)","cat":"fun","phone":"948-555-0100","note":"donne le titre du morceau radio"},
{"name":"FIB Buffalo","cat":"veh","phone":"227-555-0100","note":null},
{"name":"Cognoscenti","cat":"veh","phone":"227-555-0142","note":null},
{"name":"Comet","cat":"veh","phone":"227-555-0175","note":null},
{"name":"Turismo","cat":"veh","phone":"227-555-0147","note":null},
{"name":"Super GT","cat":"veh","phone":"227-555-0168","note":null},
{"name":"Moto NRG-900","cat":"veh","phone":"625-555-0100","note":null},
{"name":"Moto Sanchez","cat":"veh","phone":"625-555-0150","note":null},
{"name":"Hélico Annihilator","cat":"veh","phone":"359-555-0100","note":null},
{"name":"Bateau Jetmax","cat":"veh","phone":"938-555-0100","note":null},
{"name":"Moto Akuma","cat":"veh","phone":"625-555-0200","note":"DLC TBOGT"},
{"name":"Moto Vader","cat":"veh","phone":"625-555-3273","note":"DLC TBOGT"},
{"name":"Char APC","cat":"veh","phone":"272-555-8265","note":"DLC TBOGT"},
{"name":"Hélico Buzzard","cat":"veh","phone":"359-555-2899","note":"DLC TBOGT"},
{"name":"Bateau Floater","cat":"veh","phone":"938-555-0150","note":"DLC TBOGT"},
{"name":"Bullet GT","cat":"veh","phone":"227-555-9666","note":"DLC TBOGT"},
{"name":"Parachute","cat":"combat","phone":"359-555-7272","note":"DLC TBOGT"},
{"name":"Balles de sniper explosives","cat":"combat","phone":"486-555-2526","note":"DLC TBOGT"},
{"name":"Coups de poing surpuissants","cat":"fun","phone":"276-555-2666","note":"DLC TBOGT"}
    ]
  }

};
